/* HeaLoa · locale: en (US English) — DRAFT, not shipped.
 * Status: draft preview only. Reachable ONLY with ?lang=en (never remembered, never in the public switcher);
 * the page shows a small "Draft preview" badge and a footer line (draft.note) saying the English still waits for a native-speaker proofread (待母语审校). meta.complete stays false until Cindy proofreads every line
 * (she reviews English with her tool, Muse) and the en banned-word list in tests/wording.mjs is confirmed.
 * Voice: natural, warm US English for readers 50+; not a literal translation of zh.
 * Units: °F and inches (meta.tempUnit / meta.rainUnit), with °C beside water temperatures.
 * The six entries are feelings mapped to the same body states as zh:
 *   Deep rest → sleep (睡不踏实) · Warmth → cold (怕冷手脚凉) · Easy on the stomach → gut (肠胃弱)
 *   Steady and calm → bp (血压偏高) · Let go of tension → tense (心里绷得紧) · Quiet → quiet (想安静一点)
 * cindyLine stays "" — Cindy's own words only; never written or translated for her.
 */
(function (root) {
  "use strict";
  var L = root.HEALOA_LOCALES = root.HEALOA_LOCALES || {};
  L.en = {
    meta: {
      code: "en", htmlLang: "en", name: "English", complete: false, draft: true, homeRegion: "us", explainTerms: true,
      tempUnit: "F", rainUnit: "in/month",
      manifest: "manifest.en.webmanifest", /* home-screen app opens in English (start_url ./?lang=en) */
      condOrder: ["sleep", "cold", "gut", "bp", "tense", "quiet"],
      canvasFont: '-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif'
    },
    strings: {
      "meta.title": "HeaLoa · Live with the season (preview {version})",
      "meta.description": "Answer a 2-minute match and flip your 3 places for this season — each with the reasons, what to eat, what to do and what to skip.",
      "brand.sub": "Live with the season",
      "disclaimer": "This is a seasonal lifestyle guide. If you feel unwell, please check with a health professional.",
      "copyright": "",
      "match.r.cozy": "You'd like somewhere warm and cozy indoors: this place has rooms to settle into.",
      "place.actionsLead": "{n} small things to do here. Tap one to start:",
      "place.actGo": "Start",
      "imm.open": "Step inside",
      "imm.hint": "Drag the picture: near and far parts move differently.",
      "imm.hintGyro": "Turn your phone slowly, as if you were standing there looking out.",
      "imm3d.hint": "Drag to look around; hold “Walk forward” to move closer. Tap the scene to hide or show this text.",
      "imm3d.fwd": "Walk forward",
      "imm3d.back": "Step back",
      "imm3d.to2d": "View as photo",
      "imm3d.to3d": "View in 3D",
      "imm3d.note": "3D generated by World Labs from a photo",
      "imm3d.loading": "Opening the 3D scene… {pct}%",
      "imm3d.fallback": "On this phone, the photo view: drag the picture and near and far parts move differently.",
      "about.world3d": "<b>3D:</b> this one Wudang sunrise-terrace photo was given to World Labs (Marble) to make a 3D scene you can step into. Only this one photo was uploaded.",
      "imm.gyro": "Look around by turning your phone",
      "music.on": "Music: on",
      "music.off": "Music: off",
      "greet.sep": " · ",
      "reveal.summary": "Your places for the {term}: {places}",
      "reveal.open": "Tap the photo to step inside ›",
      "sound.on": "Sound: on",
      "sound.off": "Sound: off",
      "practice.stoppedNote": "Stopping early is fine. You can still keep your season card.",
      "music.noteSynth": "A soft tone made live on your phone.",
      "music.noteTrack": "A short calm track, on a loop.",
      "remind.open": "Remind me to take 3 minutes each day (optional)",
      "remind.openDone": "Want a gentle daily reminder?",
      "remind.title": "A gentle 3-minute reminder",
      "remind.lead": "If you'd like, we'll nudge you once a day. Missed one? That's fine. Do it when you feel like it.",
      "remind.whenTitle": "When?",
      "remind.custom": "Or pick your own time",
      "remind.whatTitle": "Which one?",
      "remind.t0800": "Morning 8:00",
      "remind.t1230": "Midday 12:30",
      "remind.t2130": "Bedtime 9:30 pm",
      "remind.ics": "Add to my phone's calendar (repeats daily)",
      "remind.notify": "Also remind me on this device while the app is open",
      "remind.howNote": "Your phone's own calendar does the reminding, even with the app closed, and you can delete it there any time. Web notifications only show while the app is open.",
      "remind.onNote": "Reminders on this device are on.",
      "remind.offBtn": "Stop reminding me",
      "remind.off": "Okay, no more reminders. Anything you added to your calendar can be deleted there.",
      "remind.icsDone": "Calendar file ready. Open it and tap Add.",
      "remind.notifyOn": "Okay, you'll get a reminder on this device while the app is open.",
      "remind.notifyDenied": "Notifications aren't allowed on this device. The calendar option above works instead.",
      "remind.icsTitle": "HeaLoa · {label}",
      "remind.icsBody": "If you have a moment, take 3 minutes to slow down. No time? No problem.",
      "share.saveVideo": "Save video",
      "share.howTo": "On your phone, tap Share to open your phone's own share sheet and pick any app or person. Or save the image or video first and post it from your photos.",
      "share.videoName": "healoa-story-video",
      "share.videoGuide": "Your video is ready: save it with the button below, or share it right away.",
      "share.videoMaking": "Making a 6-second video, one moment…",
      "share.videoFailed": "This device can't make the video. You can save the image instead.",
      "modal.downloadVideo": "Download video",
      "modal.shareVideo": "Share this video",
      "modal.longPressVideo": "Use the button below to save the video.",
      "about.immersive": "<b>Step inside:</b> from one photo we worked out what is near and far (a depth map) on our own computer, so near and far parts move differently when you drag or tilt your phone. No photo was uploaded for this step.",
      "about.music": "<b>Sound:</b> Tai chi, Baduanjin, and Wudang show the original practice video on a loop, with no music inside the picture. The bed is a calm excerpt (SONO, about one minute). This preview starts with sound on; Sound turns it off.",
      "punct.colon": ": ",
      "punct.listSep": ", ",
      "nav.back": "‹ Back",
      "nav.home": "Back to home",
      "legal.navAria": "Notes",
      "privacy.open": "Privacy note",
      "privacy.title": "Privacy note",
      "privacy.lead": "Everything you write here stays on this phone only.",
      "privacy.p1": "Your match answers, care log, and any line you leave are kept in this phone’s browser storage. Nothing is uploaded to a server.",
      "privacy.p2": "Body and feeling details are never uploaded, and never put into a shared image, a share link, or a URL parameter.",
      "privacy.p3": "A shared image or link carries only a random code. A line you wrote travels with the link only when you choose to send it.",
      "privacy.p4": "This preview has no server. A finished short link would look like “/s/code”.",
      "wellness.open": "Wellness note (not medical)",
      "wellness.title": "Wellness note (not medical)",
      "wellness.lead": "This is a seasonal lifestyle guide. It is not a substitute for professional advice.",
      "wellness.p1": "If you feel unwell, please check with a health professional. This app does not judge your state and does not replace an in-person talk.",
      "wellness.p2": "“Restorative” = place / atmosphere / feeling, never a result.",
      "wellness.p3": "We never promise an outcome. Practices are only for a moment of ease; however you feel is fine. Stop if you feel unwell.",
      "wellness.p4": "Shared images and links never carry your body or feeling details.",
      "season.switchAria": "Switch season",
      "season.autumn": "Fall",
      "season.winter": "Winter",
      "season.spring": "Spring",
      "season.summer": "Summer",
      "cond.groupAria": "What would feel good today?",
      "lang.switchAria": "Language",
      "social.follow": "Follow us",

      "home.headline": "Where should you be this season?",
      "home.subline": "A few quick taps about how you've been feeling, and we'll match you with 3 calm places for this season.",
      "home.hint": "No sign-up · Your answers stay on your phone",
      "home.stepsAria": "How it works",
      "home.step1": "Tap through a 2-minute match about how you've been feeling",
      "home.step2": "Flip your 3 places for this season and see why",
      "home.step3": "Step inside one, take a few calm minutes, and keep a note of it",
      "home.seasonToday": "{season} · around the {term}",
      "home.seasonAhead": "Looking ahead to {season}",
      "home.seasonPending": "Today · around the {term} · {now}. {now} ideas are still being prepared — here is {season} for now",
      "home.returnHint": "You saved a {season} card last time · Tap to open it",

      "shared.kicker": "Someone shared HeaLoa with you",
      "shared.headline": "Where should you be this season?",
      "shared.subline": "Tap through a 2-minute match and get 3 calm places for this season, picked from how you've been feeling.",
      "shared.hint": "Your answers stay on your own phone · No sign-up",

      "quiz.title": "Your 2-minute match",
      "quiz.intro": "One question at a time — just tap. Your answers stay on your phone, and you can stop any time.",
      "quiz.progress": "Question {n} of {total}",
      "quiz.skip": "None of these / Not sure",

      "result.condsAria": "Pick another",
      "result.title": "{season} · Why these places",
      "result.seasonToday": "{season} · around the {term}",
      "result.seasonAhead": "Looking ahead to {season} ({months})",
      "result.lead": "Here are a few places and ways to live that may fit this season.",
      "result.noteTitle": "Keep in mind this season",
      "result.placesTitle": "Places that may fit this season",
      "result.placesSub": "Ranked by past {season} weather and your answers · every place has a real photo",
      "result.rank": "No. {n}",
      "result.openPlace": "See this place · why it fits, what to do",
      "result.homeTitle": "Can't travel? Try this at home",
      "result.soakBtn": "10-minute foot soak timer",
      "result.skipTitle": "Better another season",
      "result.moreTitle": "More places",
      "result.moreSub": "These places could suit you too. We haven't photographed them yet, so here are just a few words, and they stay out of the top three.",
      "result.relaxCta": "Take a few calm minutes · {label}",
      "result.eatTitle": "Food and drink",
      "result.eatMore": "Enjoy more: ",
      "result.eatLess": "Go easy on: ",
      "result.eatTip": "One thing to remember: ",
      "result.eatDrink": "To drink: ",
      "result.eatNote": "Herbal teas: if you're pregnant or have an ongoing health condition, ask a health professional first.",
      "result.moveTitle": "Moving your body",
      "result.moveFollow": "Follow along (simple moves, standing or seated):",
      "result.moveWalk": "Slow-walk rhythm",
      "result.moveBaduanjin": "Baduanjin, first move",
      "result.moveTaiji": "Tai chi opening",
      "result.moveBreath": "3 minutes of slow breathing",
      "result.caution": "Please note: ",
      "result.cardCta": "Save this season's card",
      "result.kbTitle": "For your answers this season",
      "result.careplanCta": "See this season's plan",
      "careplan.title": "This season's plan",
      "careplan.lead": "Small things you can do at home this season. Save a card below if you want to keep them.",
      "careplan.backWhy": "Back to why these places",
      "practice.here": "Here · {place}",
      "practice.guidedProg": "Step {n} / {total}",
      "imm.bandwidth": "3D is about 9 MB — Wi‑Fi is better. You can also view the photo.",
      "result.srcNote": "Temperature and humidity are long-term averages for each place, not a forecast.",

      "place.cindyLine": "“{line}”",
      "place.skipLabel": "Better another season: ",
      "place.climateSkip": "{season} weather here",
      "place.climateFit": "Why it suits {season}",
      "place.eatTitle": "What to eat here",
      "place.todoTitle": "What to do here",
      "place.hotspringCaution": "Hot springs: 105°F (41°C) or cooler, 10 minutes at a time, and stand up slowly.",
      "place.homeTitle": "Can't go? Try this at home",
      "place.srcNote": "Temperatures and humidity are past averages, not a forecast. Up in the hills it feels cooler than the table says.",

      "practice.modesAria": "Choose an exercise",
      "practice.footL": "L",
      "practice.footR": "R",
      "practice.ready": "Tap Start when you're ready",
      "practice.readyGuided": "Tap Start when you're ready, then follow the words slowly",
      "practice.start": "Start",
      "practice.startAgain": "Start again",
      "practice.pause": "Pause",
      "practice.resume": "Resume",
      "practice.stop": "Stop",
      "practice.wakeNote": "Your screen stays on during the exercise",
      "practice.rounds": "{n} rounds",
      "practice.minutes": "{n} min",
      "practice.cadence": "{n} steps/min",
      "practice.beepOn": "Beat sound: on",
      "practice.beepOff": "Beat sound: off",
      "practice.safeDefault": "Never force or hold your breath. If you feel dizzy or tight in the chest, stop right away.",
      "practice.safeSoakTail": "Dry off well and put on socks.",
      "practice.safeWalk": "Walk on flat ground at your own pace. If you feel dizzy or tight in the chest, stop right away.",
      "practice.breathCue": "{phase} {n}",
      "practice.walkIn": "Breathe in · three steps",
      "practice.walkOut": "Breathe out · three steps",
      "practice.soakLast": "One minute left — get your towel ready",
      "practice.soakOn": "Soak and breathe slowly",
      "practice.guidedStep": "Step {n} of {total} · {text}",
      "practice.paused": "Paused",
      "practice.done": "All done",
      "practice.doneTitle": "All done · {time}",
      "practice.doneSub": "This was just to help you settle for a moment. However you feel is fine.",
      "practice.stopped": "Stopped (you did {time}). Tap Start whenever you'd like to go again",
      "practice.keepCard": "Keep my season card",
      "practice.again": "Once more",

      "card.title": "Your season card",
      "card.privateNote": "This card is just for you. It stays on this phone.",
      "card.showCond": "Show what I picked on my own card",
      "card.keep": "Keep it just for me",
      "card.savePng": "Save as image",
      "card.seasonToday": "{season} · around the {term}",
      "card.seasonAhead": "{season} ({months})",
      "card.head": "{who} · your {season} plan",
      "card.whoAnon": "Made for you",
      "card.lineHidden": "Your line shows on the card and in the image only when the switch above is on.",
      "card.placeLabel": "A place that fits: ",
      "card.itemEat": "Eat: {tip} Enjoy more {foods}.",
      "card.itemMove": "Move: {move}",
      "card.itemRelax": "Settle: {label} — any time you think of it.",
      "card.foot": "{disclaimer} · HeaLoa",
      "card.kept": "Saved on this phone — only you can see it. Next time you open HeaLoa, it'll be waiting on the home screen.",
      "card.keepFailed": "This phone won't let us save here. Try “Save as image” instead.",
      "card.pngName": "healoa-season-card.png",

      "share.open": "Share with someone (nothing personal is on it)",
      "share.close": "Hide sharing",
      "share.lead": "Send it to someone you'd like to share this moment with.",
      "share.panelNote": "The card only shows the season and what this app does — nothing about your body or what you picked. The link carries just a random code.",
      "share.imgAlt": "Share image preview",
      "share.qrAria": "QR code",
      "share.linkLabel": "Link",
      "share.send": "Share to Instagram, TikTok, Messages…",
      "share.copy": "Copy link",
      "share.saveImg": "Save image",
      "share.title": "HeaLoa · Live with the season",
      "share.text": "Where should you be this {season}? A 2-minute match picks 3 calm places for you.",
      "share.cardBrand": "HeaLoa · Live with the season",
      "share.cardHead": "This {season}, slow down with the season",
      "share.cardSub": "A 2-minute match picks 3 calm places for you this season.",
      "share.scanCta": "Scan with your phone camera to find your own places",
      "share.openCta": "Open the link and do your own match",
      "share.sent": "Your share sheet is open. Whether to send, and to whom, is up to you.",
      "share.copiedWithText": "This device can't share directly, so we copied the link and a short note. Just paste it in a message.",
      "share.copied": "Link copied.",
      "share.copyFailed": "Couldn't copy. Press and hold the link above to copy it.",
      "share.storyName": "healoa-story.png",
      "share.storyGuide": "Press and hold the image to save it to your photos, then share it from there.",
      "share.t.copy": "Copy link",
      "share.t.sms": "Text / iMessage",
      "share.t.whatsapp": "WhatsApp",
      "share.t.x": "X",
      "share.t.line": "LINE",
      "share.guide.sms": "Messages is open — pick who to send it to.",
      "share.guide.whatsapp": "WhatsApp is open — pick who to send it to.",
      "share.guide.x": "X is open with your post ready to go.",
      "share.guide.line": "LINE's share page is open.",

      "line.open": "Leave a line",
      "line.edit": "Change my line",
      "line.lead": "Leave a line. Make this moment yours.",
      "line.placeholder": "A few words for yourself (up to 60 characters)",
      "line.note": "It stays on this phone. If you send your card, this line goes with it — so leave out anything about your health.",
      "line.save": "Put it on my card",
      "line.cancel": "Not now",
      "line.clear": "Remove this line",
      "line.onCard": "“{line}”",
      "line.empty": "Write a few words first, then tap “Put it on my card.”",
      "line.saved": "Done. It's on your card and stays on this phone. If you send the card, the line goes with it.",
      "line.savedPrivate": "Done. It stays on this phone — it mentions your health, so it won't be sent with the card, and it shows on your own card only when the switch above is on.",
      "line.cleared": "Your line is removed.",
      "recv.lineLabel": "They left a line:",
      "recv.write": "Add a line beside theirs",
      "recv.makeOwn": "Do your own match",
      "recv.placeholder": "A few words to sit beside theirs (up to 60 characters)",
      "recv.writeNote": "You can do this once. It lives only on your phone and in the link you send back — no server. Please leave out anything about your health.",
      "recv.save": "Done",
      "recv.mineLabel": "You added:",
      "recv.sendBack": "Send it back",
      "recv.sendBackNote": "Send this link back. When they open it, they'll see your line beside theirs.",
      "recv.sendText": "I added a line beside yours.",
      "recv.alreadyWrote": "You've already added a line here.",
      "recv.private": "That line mentions health details. Try different words.",
      "recv.makeOwnHint": "Tap through a 2-minute match and your own places are ready.",
      "reply.kicker": "They added something beside yours.",
      "reply.yours": "Your line:",
      "reply.theirs": "Their line:",
      "home.stepsTitle": "How it works",
      "home.start": "Start the 2-minute match",
      "home.termExplain": "The traditional Chinese calendar has 24 mini-seasons, about two weeks each.",
      "home.rematch": "It's {term} now — match again?",
      "home.lastMatch": "Last time: {places} · Tap to see them again",
      "home.nextTerm": "The next mini-season, {next}, starts {date}. Come back then and match again — your places change with it.",
      "home.today": "Today's 3 minutes · slow breathing",
      "home.places": "See every place",
      "home.records": "My care log",
      "home.moreAria": "More",

      "first.title": "Spend one quiet minute in a place first",
      "first.lead": "The picture stays muted. Tap Start for about a minute of calm music — breathe slowly with it, or just ease your shoulders.",
      "first.ready": "When you're ready, tap Start",
      "first.start": "Start",
      "first.toQuiz": "Next: a few short questions",
      "first.skipPlaces": "Skip questions — show this season's places",
      "first.hint": "No sign-up · Your answers stay on your phone",
      "first.inhale": "Breathe in slowly {n}",
      "first.exhale": "Breathe out slowly {n}",
      "first.move": "Ease your shoulders a little",
      "first.doneCue": "That minute is done. A few questions can refine your match — or skip straight to this season's places.",
      "shared.start": "Do your own match (about 2 minutes)",
      "quiz.progressAria": "Progress",
      "quiz.multi": "Pick all that fit",
      "quiz.single": "Pick one",
      "quiz.next": "Next",
      "quiz.finish": "See my places",
      "quiz.prev": "‹ Previous",
      "quiz.exit": "Stop for now and go home",
      "reveal.title": "{season} · around the {term}",
      "reveal.lead": "Based on your answers and the season — not luck. Tap a card to turn it over.",
      "reveal.front": "Card {n}",
      "reveal.tap": "Tap to turn over",
      "reveal.match": "{season} · Your match: {kind}",
      "reveal.flipAll": "Turn them all over",
      "reveal.why": "See why",
      "reveal.fewer": "From your answers, {n} of our places fit this season. The others are set aside for now — the reasons are on the next page.",
      "reveal.none": "From your answers, staying home fits best this season. The reasons are on the next page.",
      "reveal.redo": "Match again",
      "result.termLine": "Worked out from your answers and the weather around the {term} — not luck, and no business pays to be here.",
      "result.whyLabel": "Why you",
      "result.eatLabel": "Eat: ",
      "result.doLabel": "Do: ",
      "result.avoidLabel": "Heads-up: ",
      "result.enter": "Step inside",
      "result.redo": "Match again",
      "result.nextTerm": "The next mini-season, {next}, starts {date}. Come back then and match again — your places change with it.",
      "result.atHomeFirst": "You chose staying home for now: everything below works at home, and the places are here to look at.",
      "result.usNote": "Right now every place here is in Asia, so each one is a longer trip from the US. If travel isn't possible, the at-home ideas work anywhere.",
      "result.allPlaces": "See every place (all open)",
      "place.suitsTitle": "Who it suits",
      "place.avoidTitle": "What to watch out for",
      "place.actionTitle": "One thing to do here",
      "place.allPlaces": "See every place",
      "match.r.want_warm": "You run cold: {season} here averages {t} — warm.",
      "match.r.warm_spring": "You run cold: it's a hot-spring town, and a warm soak is right there.",
      "match.r.want_cool": "You run hot: {season} here averages {t} — not muggy.",
      "match.r.even_temp": "Your readings run a little high: {season} here is warm and steady — even the coldest month averages {min}.",
      "match.r.avoid_damp": "Humid days weigh you down: humidity here is {rh}% in {season} — not too damp.",
      "match.r.avoid_dry": "You tend to feel dry: humidity here is {rh}% in {season} — not dry.",
      "match.r.gentle_pace": "You'd like an easy pace: the paths here are flat.",
      "match.r.active_ok": "You have energy to spare: there's plenty of walking here.",
      "match.r.quiet": "You're craving quiet: few people, very peaceful.",
      "match.r.nature": "You'd like to be close to nature: here it's right outside the door.",
      "match.r.open_view": "You'd like to see far: the views here are wide open.",
      "match.r.lively": "You want a little fun: the streets here are lively.",
      "match.r.scene_sea": "You picked the beach: this is right on the bay.",
      "match.r.scene_mountain": "You picked the mountains: this is up in the hills.",
      "match.r.scene_hotspring": "You picked hot springs: this is a hot-spring town.",
      "match.r.scene_forest": "You picked the forest: there are woods all around.",
      "match.r.scene_snow": "You picked snow: it snows here in winter.",
      "match.r.near": "Close to home — a weekend is enough.",
      "places.title": "Every place",
      "places.lead": "Every place is open. Tap any one you'd like to see.",
      "places.open": "Take a look",
      "records.title": "My care log",
      "records.lead": "Kept only on this phone, just for you. Delete it any time.",
      "records.empty": "Nothing here yet. After a calm few minutes, a line is added here on its own.",
      "records.row": "{date} · {term}",
      "records.atHome": "At home",
      "records.cardKept": "Kept a season card",
      "records.addNote": "Add a line",
      "records.editNote": "Change this line",
      "records.notePlaceholder": "A line for yourself (up to 60 characters, optional)",
      "records.saveNote": "Save",
      "records.delete": "Delete this line",
      "records.clearAll": "Delete everything",
      "records.cleared": "Your log has been deleted.",
      "records.nextTerm": "The next mini-season, {next}, starts {date}. Come back then and match again.",
      "practice.logged": "Added to “My care log” — on this phone only.",
      "practice.openRecords": "Open my care log",
      "date.md": "{month} {d}",
      "draft.badge": "Draft preview",
      /* queue 5 (待母语审校): shown in the footer of every en screen until Cindy (with Muse) has proofread every line */
      "draft.note": "This English is a draft — every line is still waiting for a native speaker to proofread it.",

      "modal.aria": "Image",
      "modal.imgAlt": "Card image",
      "modal.longPress": "On a phone, press and hold the image to save it to your photos.",
      "modal.download": "Download image",
      "modal.share": "Share this image",
      "modal.close": "Close",

      "about.summary": "About this demo",
      "about.versionPrefix": "Preview",
      "about.versionSuffix": "· a clickable prototype, not the finished app.",
      "about.how": "<b>How places are picked:</b> first, safety rules set aside places that don't suit you this season; then your answers (running hot or cold, beach or mountains …) add weight; finally the weather in the month of the current mini-season adjusts it. No business pays to be listed, and nothing is random. Only places with real photos are shown.",
      "about.climate": "<b>Weather numbers:</b> past averages (monthly, 2001–2020), not a forecast. Up in the hills it feels cooler than the table says. Source: NASA POWER (CC BY 4.0).",
      "about.photos": "<b>Photos:</b> A one-line impression under a place shows only when one has been provided; places without one are left blank for now.",
      "about.privacy": "<b>Privacy:</b> your answers and your care log stay on this phone (browser storage) and is never uploaded. Shared images and links carry nothing about your body or feelings — just a random code. A line you write goes into the link only when you choose to send it. This demo has no server.",
      "about.timer": "<b>Timer:</b> exercises run on real clock time, so pause, resume, and stop are accurate. Where supported, your screen stays on.",

      "rules.seasonAvg": "{season} average {t}",
      "rules.skipRain": "{avg}, about {pr} inches of rain a month — it's the rainy season, so getting out is hard.",
      "rules.skipFrigid": "{avg}, with the coldest month at {min}. Very cold, and a big jump every time you step in or out.",
      "rules.skipBpHotspring": "Outdoors: {avg}, while the springs run hot — a sharp hot-and-cold swing. For “Steady and calm,” skip it this season.",
      "rules.skipBpCold": "{avg}{dip} — on the cold side. For “Steady and calm,” start somewhere warm with gentle swings.",
      "rules.dipTo": ", dropping to {min} in {month}",
      "rules.skipBpDrop": "{avg}, dropping to {min} in {month} — it cools off quickly.",
      "rules.skipColdHands": "{avg}, {min} in {month}. If warmth is what you're after, skip it this season.",
      "rules.skipGutCold": "{avg} — on the cold side. For an easy stomach, pick somewhere a little warmer.",
      "rules.skipNightCold": "{avg}; by {month} it's down to {min}. Chilly mornings and colder nights.",
      "rules.skipHumid": "{avg}, {rh}% humidity, about {pr} inches of rain a month — hot, sticky, and rainy; {tail}",
      "rules.humidTailSleep": "nights feel stuffy.",
      "rules.humidTailGut": "it's tempting to live on iced drinks.",
      "rules.tempWarm": "warm, no stepping in and out of cold wind",
      "rules.tempMild": "not too hot, not too cold",
      "rules.tempCool": "cool, so bring a jacket",
      "rules.tempChilly": "chilly, so you'll want a warm room",
      "rules.tempCold": "cold outside, so bundle up",
      "rules.reason1": "{season} ({months}) averages {t} with {rh}% humidity: {word}.",
      "rules.reason2": "{m1} {t1} → {m3} {t3}{trend}; about {pr} inches of rain a month{rain}",
      "rules.trendBig": ", cooling noticeably through the season, so add layers as you go",
      "rules.trendStable": ", steady through the season",
      "rules.rainLow": ". Dry enough for a walk every day.",
      "rules.rainHigh": ". Rainy, so bring an umbrella and plan some indoor time.",
      "rules.rainMid": ".",
      "rules.short": "{season} average {t}, {rh}% humidity{extra}.",
      "rules.shortHotspring": ", hot springs (105°F / 41°C or cooler, 10 minutes at a time)",
      "rules.shortAltitude": ", about 6,600 ft up — check with a health professional before you go"
    },
    content: {
      privateWords: ["sleep", "stomach", "tension", "tense", "cold hands", "cold feet", "pressure", "my health", "insomn", "anxi", "diabet", "blood", "illness", "diseas", "pain", "ache", "medication"],
      conditions: { bp: "Steady and calm", sleep: "Deep rest", cold: "Warmth", gut: "Easy on the stomach", tense: "Let go of tension", quiet: "Quiet" },
      seasons: {
        autumn: { label: "Fall", months: "Sep–Nov", monthNames: ["Sep", "Oct", "Nov"] },
        winter: { label: "Winter", months: "Dec–Feb", monthNames: ["Dec", "Jan", "Feb"] }
      },
      solarTerms: ["Minor Cold", "Major Cold", "Start of Spring", "Rain Water", "Awakening of Insects", "Spring Equinox", "Clear and Bright", "Grain Rain", "Start of Summer", "Grain Buds", "Grain in Ear", "Summer Solstice", "Minor Heat", "Major Heat", "Start of Autumn", "End of Heat", "White Dew", "Autumn Equinox", "Cold Dew", "Frost's Descent", "Start of Winter", "Minor Snow", "Major Snow", "Winter Solstice"],
      /* v2026-09-28-a: one quiet line per solar term (weather / nature only, no advice; same order as solarTerms) */
      termGreetings: ["Deep winter. Stay warm and take it slow.","The coldest stretch of the year — and the closest to spring.","The air softens, and the days get brighter.","Soft rain, and the ground starts to wake up.","The first spring thunder. Everything starts to stir.","Day and night in balance — a good time to even out your pace.","Clear skies and fresh green. Get outside for a bit.","More rain, and the flowers are at their best.","Longer days and easy evening breezes.","The grain fills out. A little contentment is just right.","A busy season. Save a few slow minutes for yourself.","The longest day of the year. Find some shade and sit a while.","It's warming up. Early mornings and evenings are best for getting out.","The hottest stretch. Slow down and find somewhere cool.","Still warm, but mornings and evenings are turning cool.","The heat is easing, and the sky feels higher.","Dew on the grass in the morning. Bring a light jacket.","Day and night in balance. Fall at its best — nice for a slow walk.","The dew turns cold, and the hills grow deeper in color every day.","Maybe frost in the morning. Sunny afternoons are made for sitting in the sun.","Winter begins, and a lit window feels extra warm.","The first snow up north. Have something warm and stay cozy.","More snow. It's quiet outside, and easy to feel quiet inside.","The longest night of the year. From here, the days get a little longer."],
      places: {
        wudang: {
          name: "Wudang Mountains · Mountain Stay",
          area: "Shiyan, Hubei, China",
          alt: "A courtyard guesthouse in the Wudang Mountains",
          benefit: "A courtyard tucked into the hills. In the morning, mist drifts up from the valley and everything goes quiet — a restorative, wooded calm.",
          cindyLine: "",
          kind: "a quiet mountain retreat",
          food: ["Simple mountain greens and hot soups", "A pot of hot tea, sipped slowly on the terrace", "Go easy on spicy and greasy food"],
          todo: ["Walk slowly around the courtyard and stone steps for 20 minutes in the morning", "Try a few tai chi or Baduanjin moves (Wudang has long been linked with tai chi)", "Watch the clouds from the terrace with a cup of tea"],
          caution: ["The temperatures are for the foot of the mountain. It's colder up top, so pack an extra layer.", "Lots of stone steps: take them slowly. No need to race to the summit."],
          fit: {
            bp: "The courtyard and gentle paths are made for slow walks, and a few slow tai chi moves never ask you to strain.",
            sleep: "Night falls early in the mountains and it's very quiet — easy to go to bed with the sky.",
            cold: "Walk the courtyard when the sun is out and you'll warm up; add a layer morning and evening.",
            gut: "Simple, warm meals, and a slow stroll around the courtyard after eating.",
            tense: "Watch the clouds, listen to the mountain wind, take a few steps — your mind slows down a little.",
            quiet: "Few people, still hills. A good place to plan nothing and simply stay a few days."
          }
        },
        pattaya: {
          name: "Pattaya · By the Sea",
          area: "Chonburi, Thailand",
          alt: "Pattaya bay at dusk",
          benefit: "The sea breeze is warm, the bay turns orange at dusk, and walking by the water, your body loosens up.",
          cindyLine: "",
          kind: "a warm beach",
          food: ["Fresh coconut, clear soups, grilled fish", "Fewer iced drinks; go easy on very spicy or raw food"],
          todo: ["Walk slowly along the shore in the early morning or at dusk", "Sit in the shade, listen to the waves, and breathe slowly for a few minutes"],
          caution: ["The midday sun is strong — don't stay out in it long, and don't set the AC too cold.", "It's a long trip, so keep the schedule light and leave time for a rest after lunch."],
          fit: {
            bp: "Warm all year with small temperature swings, so you can head out for a slow walk every day.",
            sleep: "Walk by the sea and catch the morning sun, then head in early in the evening.",
            cold: "Warm all year, so hands and feet stay cozy.",
            gut: "Choose warm, simple food and skip the iced drinks and raw dishes.",
            tense: "Listen to the waves and watch the sunset — you'll loosen up a little.",
            quiet: "Skip the busy streets; the shore is quietest early in the morning."
          }
        },
        onsen: {
          name: "Kusatsu · Forest Hot Spring Town",
          area: "Gunma, Japan",
          alt: "Steam rising from the Kusatsu hot spring field and its wooden channels",
          benefit: "Steam rises slowly from the hot spring field, and as you stroll the onsen streets, you warm up bit by bit.",
          cindyLine: "",
          kind: "a steaming hot-spring town",
          food: ["Hot soba and warm soups", "A glass of warm water before and after a soak"],
          todo: ["Stroll the onsen streets and watch the steam over the spring field", "Soak your body or just your feet: choose pools 105°F (41°C) or cooler, 10 minutes at a time"],
          caution: ["Rinse your hands and feet first, stand up slowly, and don't soak alone. Skip it right after a meal or a drink, and get out if you feel dizzy.", "The town sits up in the mountains, so mornings and evenings are cool — bring an extra layer."],
          fit: {
            bp: "You can soak, but keep to this: 105°F (41°C) or cooler, 10 minutes at a time, and stand up slowly.",
            sleep: "Soak for 10 minutes one to two hours before bed, dry off, bundle up, and turn in early.",
            cold: "You'll be warm after a soak — dry off and put on socks and a hat before you head out.",
            gut: "Eat warm, simple food, and don't soak on a full stomach.",
            tense: "Walk slowly through the steam and the trees; you'll loosen up a little.",
            quiet: "The onsen streets are nearly empty early in the morning."
          }
        },
        seashrine: {
          name: "Japan Coast · Sea and Shrine",
          area: "Japan",
          alt: "Sunset over the sea, seen from a low seat by the window",
          benefit: "The evening sea turns warm. Sitting by the window is a restorative place, quiet and unhurried. The shrine roof rests under a clear sky.",
          kind: "a quiet corner by the sea",
          cindyLine: "",
          food: ["Warm soup, simple fish, hot tea", "Fewer iced drinks, and go easy on raw food"],
          todo: ["Sit by the window at dusk and breathe slowly for a few minutes", "Walk slowly in front of the shrine and look up at the roof", "If you soak, choose water at 105°F (41°C) or cooler, 10 minutes at a time"],
          caution: ["The midday sun by the sea is strong — don't stay out in it long.", "A soak: 105°F (41°C) or cooler, 10 minutes at a time, stand up slowly, and don't soak alone. Skip it right after a meal or a drink.", "Take the shrine steps slowly."],
          fit: {
            bp: "The coast swings less than a high mountain, so a slow walk is enough. If you soak: 105°F (41°C) or cooler, 10 minutes, and stand up slowly.",
            sleep: "Watch the sea for a little while at dusk, dim the lights, and turn in early.",
            cold: "The window seat is warm. Add a layer before you step out, and keep your feet warm.",
            gut: "Choose warm, simple food and skip the iced drinks.",
            tense: "Watch the sea change color, and take a slow walk by the shrine — you'll loosen up a little.",
            quiet: "When it's uncrowded, the window and the shrine front are very quiet. A good place to plan nothing."
          }
        },
        harbin: {
          name: "Harbin · Snow Country",
          area: "Heilongjiang, China",
          alt: "Snow-loaded roofs framed by pines",
          benefit: "Thick snow sits on the roofs, and pines frame the village. When the snow falls, everything goes quiet, and indoors it's warm and snug.",
          cindyLine: "",
          kind: "a quiet snowy village",
          food: ["Hot dumplings and slow-cooked stews", "A cup of hot milk tea to warm your hands"],
          todo: ["Enjoy the snow by day, but don't stay outside too long at a time", "Come back in and sip something hot, slowly"],
          caution: ["The jump between indoors and out is huge — pause at the door before stepping out.", "Roads get icy: walk slowly and wear shoes with good grip."],
          fit: {
            bp: "Big swings between warm rooms and freezing air — not a good fit this season.",
            sleep: "Warm inside, freezing outside. Don't stay out late before bed.",
            cold: "Too cold — not a good fit this season.",
            gut: "Eat warm food, and don't eat out in the cold wind.",
            tense: "The snow is very quiet. Enjoy it in short spells, and go only if you're feeling sturdy.",
            quiet: "Snowy nights are very quiet. Stay only a short while if you're feeling sturdy, and keep trips outside short."
          }
        },
        xishuangbanna: { name: "Xishuangbanna", area: "Yunnan, China", cindyLine: "" },
        tengchong: { name: "Tengchong", area: "Yunnan, China", cindyLine: "" },
        kunming: { name: "Kunming", area: "Yunnan, China", cindyLine: "" },
        phuket: { name: "Phuket", area: "Thailand", cindyLine: "" }
      },
      care: {
        bp: {
          autumn: {
            note: [
              { tag: "Rest", text: "Fall is a time to draw in: get to bed a little earlier and skip the late nights." },
              { tag: "Warmth", text: "Mornings and evenings swing cool, so bring a jacket and keep your head and neck warm." },
              { tag: "Rising", text: "When you wake up, sit for a moment before you slowly stand." }
            ],
            eat: { more: "pears, lily bulb, Chinese yam, leafy greens, tofu", less: "pickles, cured meats, very salty soups", tip: "Keep salt to less than a teaspoon a day (about 5 g).", drink: "warm water; light chrysanthemum tea (go easy if cold drinks upset your stomach)." },
            move: ["Walk slowly for 20–30 minutes a day, just enough to feel warm while you can still chat.", "Skip moves that make you hold your breath, hang upside down, or strain suddenly."],
            safety: "If you're managing a health condition, check with a health professional before a long trip or a hot spring. If you feel dizzy or tight in the chest, stop right away."
          },
          winter: {
            note: [
              { tag: "Rest", text: "Winter is a time to rest and store up: early to bed, a bit later to rise, and head out once the sun is up." },
              { tag: "Warmth", text: "Going from a warm room to the cold, pause at the door and put on a hat and scarf." },
              { tag: "Bathing", text: "Keep bath and foot-soak water from getting too hot: 105°F (41°C) or cooler, 10 minutes or less." }
            ],
            eat: { more: "daikon, Chinese yam, wood ear mushrooms, pumpkin, lightly salted hot soups", less: "hot-pot broth bases, cured meats, pickles", tip: "Keep salt to less than a teaspoon a day (about 5 g).", drink: "warm water; hawthorn and red date tea (go easy if you get heartburn)." },
            move: ["Walk slowly for 20–30 minutes around midday, when it's warmest.", "On windy, cold days, walk slowly indoors instead."],
            safety: "Hot springs and foot soaks: 105°F (41°C) or cooler, 10 minutes at a time, stand up slowly, don't soak alone, and skip it after a meal or a drink. If you're managing a health condition, check with a health professional first."
          }
        },
        sleep: {
          autumn: {
            note: [
              { tag: "Rhythm", text: "Early to bed, early to rise this fall — aim to be in bed by 10:30." },
              { tag: "Wind-down", text: "One to two hours before bed, soak your feet for 10 minutes, dim the lights, and set the phone aside." },
              { tag: "Naps", text: "Keep afternoon naps under 30 minutes." }
            ],
            eat: { more: "lily bulb, lotus seeds, millet, snow fungus, pears", less: "strong tea or coffee in the evening, late-night snacks", tip: "Stop at about 70% full at dinner, and don't eat in the two hours before bed.", drink: "a small bowl of warm millet porridge or a cup of warm milk before bed." },
            move: ["Take a 20-minute slow walk in the early evening; nothing strenuous in the two hours before bed."],
            safety: "If restless nights keep going, talk with a health professional. If the breathing exercise feels stuffy, slow down and just breathe naturally."
          },
          winter: {
            note: [
              { tag: "Rhythm", text: "Early to bed and a little later to rise this winter; get moving once the sun is up." },
              { tag: "Bedroom", text: "Keep the bedroom from getting too hot or too dry, and warm your feet under the covers first." },
              { tag: "Wind-down", text: "One to two hours before bed, soak your feet for 10 minutes, then dry off and put on socks." }
            ],
            eat: { more: "red dates, millet, walnuts, longan (a little)", less: "a heavy dinner, spicy food", tip: "Have dinner a bit earlier and keep it light.", drink: "a warm, caffeine-free drink before bed." },
            move: ["Walk slowly in the sunshine for 20 minutes during the day."],
            safety: "If restless nights keep going, talk with a health professional. If the breathing exercise feels stuffy, slow down and just breathe naturally."
          }
        },
        cold: {
          autumn: {
            note: [
              { tag: "Warmth", text: "Fall mornings and evenings are cool — keep your feet, lower back, and the back of your neck warm first." },
              { tag: "Water", text: "Fall air is dry, so sip warm water often and skip the ice." },
              { tag: "Wind-down", text: "Soak your feet for 10 minutes in the evening, then dry off and put on socks right away." }
            ],
            eat: { more: "Chinese yam, pumpkin, red dates, millet, lamb (in moderation)", less: "iced drinks, cold raw fruit", tip: "Have something warm at every meal.", drink: "red date and longan tea, or ginger with brown sugar (go easy if your throat feels dry)." },
            move: ["Once the sun is up, walk slowly for 20–30 minutes until you feel a gentle warmth.", "After sitting a while, rub your hands together and massage the soles of your feet."],
            safety: "Foot-soak water: 105°F (41°C) or cooler, 10 minutes at a time. If your feet don't feel temperature well, test the water with your hand."
          },
          winter: {
            note: [
              { tag: "Rhythm", text: "Early to bed and a little later to rise this winter; head out once the sun is up." },
              { tag: "Warmth", text: "Hat, scarf, and thick socks — keep your head, neck, and feet covered." },
              { tag: "Wind-down", text: "Soak your feet for 10 minutes, dry off, put on socks, and tuck in." }
            ],
            eat: { more: "lamb and daikon soup, red dates, ginger, walnuts", less: "anything iced or cold and raw", tip: "Always start the day with a warm breakfast.", drink: "ginger and red date tea (go easy if your throat feels dry)." },
            move: ["Walk slowly for 20 minutes around midday, when it's warmest.", "March in place indoors for 5 minutes and head out once you're warm."],
            safety: "Foot soaks and hot springs: 105°F (41°C) or cooler, 10 minutes at a time. If your feet don't feel temperature well, test the water with your hand."
          }
        },
        gut: {
          autumn: {
            note: [
              { tag: "Rhythm", text: "Eat at regular times and stop at about 70% full." },
              { tag: "Warmth", text: "Mornings and evenings are cool — keep your belly covered and your feet warm at night." },
              { tag: "Meals", text: "Eat a little more slowly, and put the phone down while you eat." }
            ],
            eat: { more: "Chinese yam, millet porridge, pumpkin, baked apple, daikon", less: "iced drinks, cold raw food, fried food, very spicy food", tip: "Start the day with a warm bowl of something.", drink: "warm millet porridge, warm water." },
            move: ["Wait half an hour after eating, then walk slowly for 15–20 minutes.", "Before bed, gently rub your belly in clockwise circles for 3 minutes."],
            safety: "If your stomach stays upset or feels very different from usual, check with a health professional."
          },
          winter: {
            note: [
              { tag: "Rhythm", text: "Have a warm breakfast; don't head out on an empty stomach." },
              { tag: "Warmth", text: "Keep your belly and feet warm, and keep the chill out." },
              { tag: "Meals", text: "Save hot pot and barbecue for now and then, and stop at about 70% full." }
            ],
            eat: { more: "Chinese yam, millet, pumpkin, red dates, warm noodle soup", less: "cold raw food, iced food, very greasy food", tip: "Eat slowly and chew well.", drink: "warm water, red date and millet porridge." },
            move: ["Wait half an hour after eating, then walk slowly for 15–20 minutes.", "Before bed, gently rub your belly in clockwise circles for 3 minutes."],
            safety: "If your stomach stays upset or feels very different from usual, check with a health professional."
          }
        },
        tense: {
          autumn: {
            note: [
              { tag: "Space", text: "Leave 10 minutes a day to do nothing at all — look at the sky, look at the trees." },
              { tag: "Rhythm", text: "Get to bed earlier this fall, and put the phone across the room." },
              { tag: "Outside", text: "Get 20 minutes of daylight outdoors." }
            ],
            eat: { more: "lily bulb, millet, bananas, a few nuts", less: "strong tea, coffee, very sweet snacks", tip: "Eat on time, not too hungry and not too full.", drink: "light jasmine tea (go easy after 3 p.m.)." },
            move: ["Follow the slow-walk rhythm for 20 minutes, counting each step."],
            safety: "If the tension won't let up and it's getting in the way of eating or sleeping, talk with a health professional."
          },
          winter: {
            note: [
              { tag: "Sunlight", text: "Head out around midday for 20 minutes of sun." },
              { tag: "Rhythm", text: "Early to bed and a little later to rise this winter; skip the late nights." },
              { tag: "Space", text: "Leave 10 minutes a day for one slow little thing, like making a pot of tea." }
            ],
            eat: { more: "millet, red dates, walnuts, warm soups", less: "strong tea, coffee, very sweet snacks", tip: "Eat on time, and eat warm.", drink: "warm red date tea." },
            move: ["Follow the slow-walk rhythm for 20 minutes around midday, when it's warmest."],
            safety: "If the tension won't let up and it's getting in the way of eating or sleeping, talk with a health professional."
          }
        },
        quiet: {
          autumn: {
            note: [
              { tag: "Space", text: "Find the same quiet stretch of time each day, and plan a little less." },
              { tag: "Rhythm", text: "Early to bed, early to rise this fall — follow the daylight." },
              { tag: "Water", text: "Fall air is dry, so sip warm water often." }
            ],
            eat: { more: "pears, lily bulb, Chinese yam, millet", less: "very spicy or salty food, late dinners out", tip: "Light, warm, and on time.", drink: "a pot of light tea, sipped slowly." },
            move: ["Take a 20-minute walk on your own — no earbuds, just the sound of your steps."],
            safety: "If you feel unwell, check with a health professional."
          },
          winter: {
            note: [
              { tag: "Space", text: "Winter is for staying in: fewer outings, more quiet time at home." },
              { tag: "Rhythm", text: "Early to bed and a little later to rise; head out once the sun is up." },
              { tag: "Warmth", text: "Keep the room cozy and make a pot of hot tea." }
            ],
            eat: { more: "Chinese yam, daikon, millet, warm soups", less: "anything iced or very spicy", tip: "Eat warm, and stop at about 70% full.", drink: "a pot of hot tea, sipped slowly." },
            move: ["Take a 20-minute walk on your own around midday, when it's warmest."],
            safety: "If you feel unwell, check with a health professional."
          }
        }
      },
      practices: {
        breath46: {
          label: "Slow breathing · in 4, out 6",
          short: "Slow breathing",
          intro: "Follow the circle: breathe in slowly through your nose as it grows, and breathe out slowly as it shrinks. No holding your breath.",
          phases: ["Breathe in", "Breathe out"]
        },
        breathNight: {
          label: "Bedtime slow breathing · in 4, out 6",
          short: "Bedtime breathing",
          intro: "Lying down or seated. Follow the circle: breathe in slowly for 4 as it grows, out slowly for 6 as it shrinks. No holding your breath. Ten rounds, under 2 minutes.",
          phases: ["Breathe in", "Breathe out slowly"]
        },
        walk: {
          label: "Slow-walk rhythm",
          short: "Slow walk",
          intro: "Walk slowly to the “L · R” beat: three steps breathing in, three steps breathing out. Indoors, in a hallway, or in the park."
        },
        soak: {
          label: "Foot soak / hot spring timer",
          short: "Foot soak",
          intro: "Water 105°F (41°C) or cooler — warm, not hot, to the touch — for 10 minutes or less. Rinse your hands and feet first, and stand up slowly."
        },
        sitEasy: {
          label: "Seated, 3 minutes",
          short: "Seated 3 min",
          intro: "Not into exercise? That's fine. You can do this sitting in a chair, with small, slow moves. Skip any step that doesn't feel right.",
          steps: [
            "Sit toward the front of the chair, feet flat on the floor, back gently tall.",
            "Breathe in and slowly lift your shoulders; breathe out and let them drop. A few times.",
            "Turn your head slowly to the left, then to the right, only as far as feels comfortable.",
            "Gently make fists and open your hands, then circle your wrists a few times.",
            "Keep your heels down and tap your toes, then tap your heels.",
            "Rest a hand on your belly and breathe naturally, feeling it rise and fall.",
            "Finally, sit and look out the window or into the distance. Nothing else to do."
          ]
        },
        baduanjin1: {
          label: "Baduanjin, first move · Holding up the sky",
          short: "Baduanjin 1",
          intro: "Start with the first move — standing or seated. If your shoulders or neck complain, only lift as high as feels comfortable.",
          steps: [
            "Stand with your feet shoulder-width apart (or sit), shoulders relaxed.",
            "Lace your fingers in front of your belly, palms up, and breathe in slowly.",
            "Turn your palms up past your chest and press toward the sky, eyes following your hands.",
            "Stay up there for two seconds — no holding your breath, just breathe naturally.",
            "Breathe out slowly and let your arms float down by your sides, back to your belly.",
            "Once more: breathe in and lift, breathe out and lower.",
            "A third time, as slowly as you like, then stand still for a moment."
          ]
        },
        taiji1: {
          label: "Tai chi · Opening",
          short: "Tai chi",
          intro: "Start with the opening move: slow, soft, in time with your breath. If your knees complain, bend less.",
          steps: [
            "Stand with your feet together, body relaxed, eyes looking ahead.",
            "Step your left foot out gently to shoulder width.",
            "Slowly raise both arms in front of you to shoulder height as you breathe in.",
            "Soften your knees and gently press your hands down to your belly as you breathe out.",
            "Once more: breathe in and lift, breathe out and press down.",
            "A third time, as slowly as you like, then stand still for a moment."
          ]
        }
      },
      careGeneric: {
        autumn: { eat: "Eat: fall air is dry, so enjoy moist foods such as pears, lily bulb and white fungus.", move: "Move: a slow 20–30 minute walk each day — a light sweat, still able to chat.", relax: "Settle: slow breathing, in for 4, out for 6, any time you think of it.", safety: "Go at your own pace; if anything feels off, stop and rest." },
        winter: { eat: "Eat: warm food, not too full — radish, Chinese yam, millet, warm soup.", move: "Move: a slow 20-minute walk in the warm middle of the day; walk indoors on windy days.", relax: "Settle: slow breathing, in for 4, out for 6, any time you think of it.", safety: "Go at your own pace; if anything feels off, stop and rest." }
      },
      homePlan: {
        bp: ["Soak your feet for 10 minutes, one to two hours before bed (105°F / 41°C or cooler)", "3 minutes of slow breathing: in for 4, out for 6, no holding", "A slow 20–30 minute walk in a nearby park"],
        sleep: ["Soak your feet for 10 minutes, one to two hours before bed", "Dim the lights and set the phone aside", "Ten rounds of bedtime slow breathing before you lie down: in for 4, out for 6"],
        cold: ["Soak your feet for 10 minutes in the evening, then put on socks right away", "A cup of warm red date tea", "A slow 20-minute walk when the sun is out"],
        gut: ["A warm bowl of porridge for breakfast", "A slow 15-minute walk half an hour after meals", "Gently rub your belly in clockwise circles for 3 minutes before bed"],
        tense: ["Follow the slow-walk rhythm for 20 minutes", "3 minutes of slow breathing", "10 minutes a day of doing nothing at all"],
        quiet: ["Find the same quiet stretch of time each day", "Make a pot of tea and sip it slowly", "3 minutes of slow breathing while you look out the window"]
      },
      quiz: {
        cold: "Are your hands and feet often cold — colder than the people around you?",
        sleep: "Is it hard to fall asleep at night, or do you often wake up in the middle of the night?",
        gut: "Does your stomach get upset after something cold or greasy?",
        tense: "Lately, do you feel wound up and find it hard to relax?",
        bp: "At checkups, are your numbers often a little higher than you'd like?"
      },
      /* v4 quiz — US draft (plan v4 §3.2). Final wording pending Cindy + Muse.
       * q1.bp is a stand-in phrasing only; the exact words are for Cindy and Muse to decide.
       * q8 "A few nights away": the draft's "(Hawaii counts!)" is left out until a Hawaii place is live. */
      quiz: {
        q1: { q: "Anything your body's been telling you lately?", hint: "Pick all that fit", opts: { bp: "My check-up readings run a little high", sleep: "I don't sleep through the night", cold: "My hands and feet run cold", gut: "My stomach is sensitive", lowEnergy: "Low on energy", stiff: "Stiff neck, shoulders or back", heavy: "Feeling heavy, not in the mood to move", eyes: "Tired eyes from screens", fine: "I feel pretty good" } },
        q2: { q: "Do you run hot or cold?", hint: "Pick one", opts: { cold: "I'm always reaching for a sweater", hot: "I'm always the one turning on the AC", same: "Somewhere in between", unsure: "Not sure" } },
        q3: { q: "Which sounds more like you?", hint: "Pick one", opts: { dry: "Dry mouth, dry skin", damp: "I feel heavy and sluggish when it's humid", neither: "Neither" } },
        q4: { q: "How's your energy these days?", hint: "Pick one", opts: { plenty: "Plenty", soso: "So-so", low: "I run out of steam fast" } },
        q5: { q: "What's your everyday rhythm?", hint: "Pick all that fit", opts: { late: "Late nights", sitting: "Sitting most of the day", screen: "Lots of phone and computer time", noexercise: "Not really into exercise", meals: "Meals at odd hours", iced: "Lots of iced drinks", busy: "Caring for family, little time for myself", regular: "Pretty regular routine" } },
        q6: { q: "How are you feeling inside?", hint: "Pick all that fit", opts: { tense: "Wound up", quiet: "Craving quiet", air: "Need some fresh air", fun: "Want a little fun", sun: "Want some sunshine", green: "Want to be surrounded by nature", alone: "Want some time alone", calm: "Pretty calm" } },
        q7: { q: "Where would you love to be?", hint: "Pick all that fit", opts: { sea: "Beach", mountain: "Mountains", hotspring: "Hot springs", forest: "Forest", snow: "Snow", view: "Somewhere with a far view (cloud sea, open ocean)", cozy: "A warm, cozy room", any: "Surprise me" } },
        q8: { q: "What's realistic this season?", hint: "Pick one", opts: {}, marketOpts: { drive: "A weekend drive", nights: "A few nights away", asia: "A bigger trip — even Asia", home: "Staying home for now" } }
      },
      placeActions: {
        wudang: { label: "Slow walk on the courtyard steps · 10 min", short: "Courtyard walk", intro: "Picture the stone steps of the courtyard and walk slowly to a left · right beat: three steps breathing in, three steps breathing out. A hallway or any room works too." },
        pattaya: { label: "Slow breathing by the bay · in 4, out 6 · 3 min", short: "Bayside breathing", intro: "Look out at the evening bay and follow the circle: breathe in through your nose for 4 seconds as it grows, out for 6 as it shrinks — like waves coming and going. No holding your breath." },
        onsen: { label: "Foot-soak timer · 10 min (105°F or cooler)", short: "Foot-soak timer", intro: "Like sitting at a footbath in the hot-spring town: water 105°F (41°C) or cooler (warm to the touch, never hot), 10 minutes at most. Rinse your hands and feet first, and stand up slowly." },
        seashrine: { label: "Sea at the window · slow breathing, 3 minutes", short: "Sea breathing", intro: "Watch the sea through the window and follow the circle: breathe in slowly for 4 seconds as it grows, and out for 6 as it shrinks. Don't hold your breath." },
        harbin: { label: "Warm drink, snow view · slow breathing 3 min", short: "Snow-view breathing", intro: "Hold a warm drink, look out the window and follow the circle: breathe in for 4 seconds as it grows, out for 6 as it shrinks. No holding your breath." }
      },
      placeActivities: {
        wudang: [
          { label: "Tai chi opening move on the sunrise terrace", short: "Terrace tai chi", intro: "Picture the terrace above the cloud sea at sunrise: slow, soft, with your breath. Start with the opening move. Bend your knees less if they complain." },
          { label: "Baduanjin, first move, by the tea window", short: "Tea-window Baduanjin", intro: "Picture the tea corner by the guesthouse window: standing or sitting, raise both hands slowly, only as high as your shoulders like." },
          { label: "Sit in the cliff pavilion, 3 minutes", short: "Pavilion sit", intro: "Picture the pavilion at the cliff edge: a few small moves in your chair, then look into the distance." }
        ],
        pattaya: [
          { label: "An evening walk along the bay", short: "Bay walk", intro: "Picture Pattaya's bay at dusk: walk slowly to the left-right beat, three steps in, three steps out." },
          { label: "Sit by the shady pool, 3 minutes", short: "Poolside sit", intro: "Picture the long pool under the trees: a few small seated moves while you listen to the water." }
        ],
        onsen: [
          { label: "Stroll the onsen streets and watch the steam", short: "Onsen stroll", intro: "Picture the steam rising over the spring field: walk slowly to the left-right beat. Indoors or a hallway works too." },
          { label: "Sit for a while after a soak, 3 minutes", short: "After-soak sit", intro: "Stand up slowly after soaking. Sit down, do a few small moves, and sip some warm water." }
        ],
        seashrine: [
          { label: "A slow walk in front of the shrine", short: "Shrine walk", intro: "Like walking under the shrine roof: follow the left · right rhythm, slowly. If there are steps, stay on the flat path." },
          { label: "Sit by the window and watch the sea · 3 minutes", short: "Window seat", intro: "Like sitting at the glass: a few tiny moves, then just look at the water." }
        ],
        harbin: [
          { label: "Sit in a warm room, 3 minutes", short: "Warm-room sit", intro: "Picture coming in from the snow to a warm room: a few small seated moves, then sip something hot." },
          { label: "Slow breathing by the lights and snow", short: "Lantern breathing", intro: "Picture the lights glowing in the snow at night: follow the circle, breathe in slowly for 4 seconds as it grows and out for 6 as it shrinks. No holding." }
        ]
      },
      monthShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
      /* Cindy's own "why Asia" line (plan v4 §2.2). Empty until she writes it; empty renders nothing. */
      asiaLine: ""
    }
  };
})(typeof window !== "undefined" ? window : globalThis);
