/**
 * 3D world view tests (v2026-09-28-b). The Wudang immersive view shows the World Labs Marble world made from Cindy's
 * terrace photo (Spark + three.js, vendored), and falls back to the 2.5D photo view when WebGL2 is missing, the phone is
 * weak, or loading fails.
 *  1. static: the asset paths in app/data.js exist in the repo, are .spz / .jpg, and are small enough for GitHub Pages;
 *     the libraries are vendored + pinned via the import map; the fallback code path exists.
 *  2. browser: the 3D view requests its own .spz path (200) and the vendored modules; ?no3d=1 and a failing module both
 *     land on the 2.5D view; the World Labs note and the copyright line are shown; nothing about the person is in the URL.
 * Run: node tests/world3d.mjs
 */
import { chromium } from "playwright";
import fs from "fs";
import path from "path";
import vm from "vm";
import { startServer, ROOT } from "./lib/server.mjs";

const results = [];
function check(name, ok, detail) {
  results.push({ name, ok: !!ok, detail: detail ?? null });
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}${detail != null ? " — " + (typeof detail === "string" ? detail : JSON.stringify(detail)).slice(0, 400) : ""}`);
}
const read = (f) => fs.readFileSync(path.join(ROOT, f), "utf8");
const ctx = {}; ctx.globalThis = ctx; vm.createContext(ctx);
for (const f of ["app/i18n/zh.js", "app/i18n/en.js", "app/i18n/ja.js", "app/i18n/es.js", "app/i18n/i18n.js", "app/social.js", "app/share-targets.js", "app/data.js"]) vm.runInContext(read(f), ctx, { filename: f });
const D = ctx.HEALOA_DATA;
const W = D.IMMERSIVE.wudang && D.IMMERSIVE.wudang.world3d;
const MB = (f) => fs.statSync(path.join(ROOT, f)).size / 1048576;

// ---- 1. static ----
{
  const files = W ? [W.spz, W.spzLow, W.pano].filter(Boolean) : [];
  const sizes = Object.fromEntries(files.map((f) => [f, fs.existsSync(path.join(ROOT, f)) ? +MB(f).toFixed(2) : null]));
  check("world3d: Wudang has spz (500k) + spzLow (100k) + pano, all files in the repo (no remote / signed URLs)",
    !!W && /^assets\/places\/wudang\/3d\/.+\.spz$/.test(W.spz) && /\.spz$/.test(W.spzLow) && /\.(jpe?g|webp|png)$/.test(W.pano) && files.every((f) => sizes[f] != null && !/^https?:/.test(f)), sizes);
  check("world3d: every file < 50 MB (GitHub Pages; hard limit 100 MB) and the 100k file is smaller than the 500k file",
    files.every((f) => sizes[f] > 0 && sizes[f] < 50) && sizes[W.spzLow] <= sizes[W.spz], sizes);
  check("world3d: scale (metric_scale_factor) is a positive number; walking radius is small (≤ 3 m)", W && W.scale > 0 && W.maxWalk > 0 && W.maxWalk <= 3, { scale: W && W.scale, maxWalk: W && W.maxWalk });
  const html = read("index.html"), map = JSON.parse((html.match(/<script type="importmap">([\s\S]*?)<\/script>/) || [])[1] || "{}").imports || {};
  const local = Object.values(map).every((u) => /^\.\/vendor\/[a-z]+-\d+\.\d+\.\d+\//.test(u) && fs.existsSync(path.join(ROOT, u.replace(/^\.\//, "").replace(/\/$/, ""))));
  check("world3d: three + Spark are vendored, version-pinned, and mapped by the import map (no CDN)", local && map.three && map["@sparkjsdev/spark"] && fs.existsSync(path.join(ROOT, "vendor/three-0.186.1/addons/postprocessing/Pass.js")), map);
  const app = read("app/app.js");
  check("world3d: fallback path — can3d() (WebGL2 + not a weak phone) gates the 3D view; load error / timeout / module failure → immStart() 2.5D",
    /function can3d\(/.test(app) && /getContext\("webgl2"\)/.test(app) && /deviceMemory/.test(app) && /fail\("timeout"\)/.test(app) && /fail\("load"\)/.test(app) && /fail\("module"\)/.test(app) && /immStart\(cfg, why\)/.test(app));
  check("world3d: note 「3D 由 World Labs 根据 Cindy Yang 的照片生成」 in zh (en: 3D generated by World Labs from Cindy Yang's photo)",
    ctx.HEALOA_LOCALES.zh.strings["imm3d.note"] === "3D 由 World Labs 根据 Cindy Yang 的照片生成" && ctx.HEALOA_LOCALES.en.strings["imm3d.note"] === "3D generated by World Labs from Cindy Yang's photo");
}

// ---- 2. browser ----
const { server, base } = await startServer();
const browser = await chromium.launch({ args: ["--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"] });
const pageErrors = [];
async function open(q, routes) {
  const c = await browser.newContext({ viewport: { width: 390, height: 844 }, locale: "zh-CN" });
  const p = await c.newPage();
  p.on("pageerror", (e) => pageErrors.push(String(e)));
  if (routes) for (const [pat, fn] of Object.entries(routes)) await p.route(pat, fn);
  const req = [];
  p.on("response", (r) => req.push([new URL(r.url()).pathname.replace(/^\/healoa-base-prototype-preview\//, ""), r.status()]));
  await p.goto(base + q);
  return { c, p, req };
}
const vis = (p, id) => p.evaluate((id) => { const e = document.getElementById(id); return !!(e && !e.classList.contains("hidden") && e.offsetParent !== null); }, id);
try {
  // 2a. WebGL2 available → the 3D view asks for its own asset path; otherwise it must be on the 2.5D fallback
  {
    const { c, p, req } = await open("?imm=wudang");
    await p.waitForFunction(() => { const s = window.__healoa && window.__healoa.w3d(); return s && (s.ready || s.fail || !document.getElementById("vImmersive").classList.contains("is3d")); }, null, { timeout: 90000 }).catch(() => {});
    const webgl2 = await p.evaluate(() => !!document.createElement("canvas").getContext("webgl2"));
    const s = await p.evaluate(() => window.__healoa.w3d());
    const view = await p.evaluate(() => document.querySelector(".view:not(.hidden)").dataset.view);
    const got = (f) => req.some(([u, st]) => u === f && st === 200);
    const url = await p.evaluate(() => location.href);
    if (webgl2) {
      check("3D view (WebGL2): ?imm=wudang opens the immersive view, loads the vendored modules + its own .spz path (200), and becomes ready",
        view === "immersive" && got(W.spz) && req.some(([u, st]) => /^vendor\/spark-2\.2\.0\/spark\.module\.min\.js/.test(u) && st === 200) && req.some(([u, st]) => /^app\/world3d\.js/.test(u) && st === 200) && s.ready && !!(await p.$("#imm3dCanvas")),
        { view, s, spz: got(W.spz) });
      check("3D view: World Labs note + copyright line visible, walk buttons + 「换成照片看」 shown; URL carries no body / quiz info",
        (await vis(p, "imm3dNote")) && (await p.textContent("#imm3dNote")) === "3D 由 World Labs 根据 Cindy Yang 的照片生成" && (await p.$$eval("#vImmersive .copyright", (els) => els.some((e) => e.offsetParent)))
        && (await vis(p, "btnImmFwd")) && (await vis(p, "btnImmMode")) && [...new URL(url).searchParams.keys()].every((k) => ["imm", "lang"].includes(k)), url);
      await p.click("#btnImmMode");
      check("3D view: 「换成照片看」 switches to the 2.5D photo view and removes the 3D canvas; 「换成 3D 看」 is offered back",
        !(await p.$("#imm3dCanvas")) && (await vis(p, "immCanvas")) && (await p.textContent("#btnImmMode")) === "换成 3D 看");
    } else {
      check("3D view (no WebGL2 in this browser): falls back to the 2.5D photo view", view === "immersive" && !(await p.$("#imm3dCanvas")) && !s.ready, s);
    }
    await c.close();
  }
  // 2b. ?no3d=1 (stands in for a weak phone / no WebGL2) → 2.5D, and the .spz is never downloaded
  {
    const { c, p, req } = await open("?imm=wudang&no3d=1");
    await p.waitForTimeout(1500);
    check("fallback: without 3D support the immersive view is the 2.5D photo view (no 3D canvas, no .spz download, no World Labs note)",
      !(await p.$("#imm3dCanvas")) && ((await vis(p, "immCanvas")) || (await vis(p, "immFallback"))) && !req.some(([u]) => /\.spz$/.test(u)) && !(await vis(p, "imm3dNote")));
    await c.close();
  }
  // 2c. module fails to load → 2.5D fallback with a friendly hint
  {
    const { c, p } = await open("?imm=wudang", { "**/vendor/spark-2.2.0/**": (r) => r.fulfill({ status: 404, body: "" }) });
    await p.waitForFunction(() => window.__healoa && window.__healoa.w3d().fail, null, { timeout: 30000 }).catch(() => {});
    const s = await p.evaluate(() => window.__healoa.w3d());
    const webgl2 = await p.evaluate(() => !!document.createElement("canvas").getContext("webgl2"));
    check("fallback: if the 3D libraries fail to load, the view falls back to the 2.5D photo view with the fallback hint",
      !webgl2 || (s.fail === "module" && !(await p.$("#imm3dCanvas")) && (await p.textContent("#immHint")) === ctx.HEALOA_LOCALES.zh.strings["imm3d.fallback"]), s);
    await c.close();
  }
  // 2d. the .spz fails (404) → fallback too
  {
    const { c, p } = await open("?imm=wudang", { "**/*.spz": (r) => r.fulfill({ status: 404, body: "" }) });
    await p.waitForFunction(() => window.__healoa && window.__healoa.w3d().fail, null, { timeout: 30000 }).catch(() => {});
    const s = await p.evaluate(() => window.__healoa.w3d());
    const webgl2 = await p.evaluate(() => !!document.createElement("canvas").getContext("webgl2"));
    check("fallback: if the .spz file cannot be loaded, the view falls back to the 2.5D photo view", !webgl2 || (!!s.fail && !(await p.$("#imm3dCanvas"))), s);
    await c.close();
  }
} finally {
  await browser.close(); server.close();
}
const real = pageErrors.filter((e) => !/spz|splat|Failed to fetch|404/i.test(e));
check("no page errors during the 3D run (the deliberate 404 cases excepted)", real.length === 0, real.slice(0, 5));
const failed = results.filter((r) => !r.ok);
console.log(`\nworld3d: ${results.length - failed.length}/${results.length} PASS`);
if (process.env.HEALOA_RESULTS_DIR) fs.writeFileSync(path.join(process.env.HEALOA_RESULTS_DIR, "world3d.json"), JSON.stringify(results, null, 2));
process.exit(failed.length ? 1 : 0);
